# Generated by Django 5.1.1 on 2024-10-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facerecognition',
            name='id',
        ),
        migrations.AddField(
            model_name='facerecognition',
            name='mssv',
            field=models.CharField(default='unknown', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facerecognition',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
